import { useEffect, useMemo, useState } from 'react';
import { Activity, MapPin, Users, RefreshCw, ShieldAlert } from 'lucide-react';
import { cloudSelect } from '@/lib/seyajCloud';
import { PageToolbar, Btn, StatusBadge } from '@/components/ui-kit';

export default function Monitor() {
  const [rows, setRows] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const load = async () => { setLoading(true); try { const data = await cloudSelect('attendance', 'id,employee_number,attendance_date,check_in,check_out,attendance_status,site_id,project_id', 'order=attendance_date.desc,check_in.desc&limit=100'); setRows(data); } finally { setLoading(false); } };
  useEffect(()=>{ void load(); const t=window.setInterval(()=>void load(),60000); return()=>window.clearInterval(t); },[]);
  const stats = useMemo(()=>({total:rows.length,present:rows.filter(r=>['حاضر','present'].includes(r.attendance_status)).length,late:rows.filter(r=>String(r.attendance_status).includes('متأخر')||String(r.attendance_status).includes('late')).length}),[rows]);
  return <div><PageToolbar title="المراقبة التشغيلية" subtitle="متابعة الحضور والحالة التشغيلية من قاعدة البيانات" actions={<Btn variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?'h-4 w-4 animate-spin':'h-4 w-4'}/>تحديث</Btn>}/><div className="grid gap-3 md:grid-cols-3 mb-5"><div className="rounded-xl border p-4"><Activity className="h-5 w-5 text-emerald-600"/><div className="mt-2 text-xs text-muted-foreground">السجلات</div><div className="text-2xl font-extrabold">{stats.total}</div></div><div className="rounded-xl border p-4"><Users className="h-5 w-5"/><div className="mt-2 text-xs text-muted-foreground">حاضر</div><div className="text-2xl font-extrabold">{stats.present}</div></div><div className="rounded-xl border p-4"><ShieldAlert className="h-5 w-5"/><div className="mt-2 text-xs text-muted-foreground">متأخر/تنبيه</div><div className="text-2xl font-extrabold">{stats.late}</div></div></div><div className="rounded-xl border overflow-hidden"><div className="border-b p-4 font-bold">آخر سجلات الحضور</div>{rows.slice(0,40).map(r=><div key={r.id} className="flex items-center justify-between border-b px-4 py-3 last:border-0"><div><div className="font-bold text-sm">{r.employee_number}</div><div className="text-xs text-muted-foreground flex items-center gap-1"><MapPin className="h-3.5 w-3.5"/>موقع #{r.site_id||'—'} · مشروع #{r.project_id||'—'}</div></div><div className="text-left"><div className="text-xs">{r.attendance_date} {r.check_in||''}</div><StatusBadge value={r.attendance_status||'—'}/></div></div>)}{!rows.length&&!loading&&<div className="p-8 text-center text-sm text-muted-foreground">لا توجد بيانات حضور متاحة حاليًا أو لا تسمح الصلاحيات بعرضها.</div>}</div></div>;
}
