import { Toaster } from '@/components/ui/sonner';
import { TooltipProvider } from '@/components/ui/tooltip';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { StoreProvider } from '@/lib/store';
import { AuthProvider, useAuth } from '@/contexts/AuthContext';
import Layout from '@/components/Layout';
import Dashboard from '@/pages/Dashboard';
import Employees from '@/pages/Employees';
import Attendance from '@/pages/Attendance';
import Projects from '@/pages/Projects';
import Sites from '@/pages/Sites';
import Zones from '@/pages/Zones';
import Roles from '@/pages/Roles';
import Requests from '@/pages/Requests';
import Patrols from '@/pages/Patrols';
import Handovers from '@/pages/Handovers';
import Custody from '@/pages/Custody';
import Reports from '@/pages/Reports';
import SmartReports from '@/pages/SmartReports';
import Settings from '@/pages/Settings';
import SitesCapacity from '@/pages/SitesCapacity';
import FieldVisits from '@/pages/FieldVisits';
import Violations from '@/pages/Violations';
import Finance from '@/pages/Finance';
import HrLeaves from '@/pages/hr/Leaves';
import HrPayroll from '@/pages/hr/Payroll';
import HrEmployees from '@/pages/hr/HrEmployees';
import HrAudit from '@/pages/hr/Audit';
import HrDashboard from '@/pages/hr/HrDashboard';
import Recruitment from '@/pages/Recruitment';
import ImportEmployees from '@/pages/hr/ImportEmployees';
import ImportPayroll from '@/pages/hr/ImportPayroll';
import MobileApp from '@/pages/MobileApp';
import MapCenter from '@/pages/MapCenter';
import AuthReturn from '@/pages/AuthReturn';
import Alerts from '@/pages/Alerts';
import AuditLog from '@/pages/AuditLog';
import Login from '@/pages/Login';
import Monitor from '@/pages/Monitor';
import BusinessHub from '@/pages/BusinessHub';
import AIControlCenter from '@/pages/AIControlCenter';

const queryClient = new QueryClient();
function ProtectedRoute({ children }: { children: React.ReactNode }) { const requireAuth = import.meta.env.VITE_REQUIRE_AUTH === 'true'; const { user, loading } = useAuth(); if (!requireAuth) return <>{children}</>; if (loading) return <div className="min-h-screen bg-slate-950 text-white flex items-center justify-center">جاري التحقق من الجلسة...</div>; if (!user) return <Navigate to="/login" replace />; return <>{children}</>; }
const AppRoutes = () => (<Routes><Route path="/login" element={<Login />} /><Route path="/monitor" element={<Monitor />} /><Route path="/app" element={<MobileApp />} /><Route path="/auth/callback" element={<AuthReturn />} /><Route element={<ProtectedRoute><Layout /></ProtectedRoute>}><Route path="/" element={<Dashboard />} /><Route path="/business" element={<BusinessHub />} /><Route path="/ai-control" element={<AIControlCenter />} /><Route path="/employees" element={<Employees />} /><Route path="/attendance" element={<Attendance />} /><Route path="/projects" element={<Projects />} /><Route path="/sites" element={<Sites />} /><Route path="/zones" element={<Zones />} /><Route path="/roles" element={<Roles />} /><Route path="/requests" element={<Requests />} /><Route path="/patrols" element={<Patrols />} /><Route path="/handovers" element={<Handovers />} /><Route path="/custody" element={<Custody />} /><Route path="/alerts" element={<Alerts />} /><Route path="/audit" element={<AuditLog />} /><Route path="/reports" element={<Reports />} /><Route path="/smart-reports" element={<SmartReports />} /><Route path="/sites-capacity" element={<SitesCapacity />} /><Route path="/field-visits" element={<FieldVisits />} /><Route path="/violations" element={<Violations />} /><Route path="/settings" element={<Settings />} /><Route path="/finance" element={<Finance />} /><Route path="/hr/leaves" element={<HrLeaves />} /><Route path="/hr/payroll" element={<HrPayroll />} /><Route path="/hr/employees" element={<HrEmployees />} /><Route path="/hr/employees/:code" element={<HrEmployees />} /><Route path="/hr/audit" element={<HrAudit />} /><Route path="/hr/dashboard" element={<HrDashboard />} /><Route path="/recruitment" element={<Recruitment />} /><Route path="/hr/import-employees" element={<ImportEmployees />} /><Route path="/hr/import-payroll" element={<ImportPayroll />} /><Route path="/map-center" element={<MapCenter />} /><Route path="*" element={<Navigate to="/" replace />} /></Route></Routes>);
const App = () => (<QueryClientProvider client={queryClient}><AuthProvider><StoreProvider><TooltipProvider><Toaster /><BrowserRouter><AppRoutes /></BrowserRouter></TooltipProvider></StoreProvider></AuthProvider></QueryClientProvider>);
export default App; export { AppRoutes };